PortfolioProject/Controllers/ContactsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PortfolioProject.Data;
using PortfolioProject.Models;

namespace PortfolioProject.Controllers
{
    /// <summary>
    /// The controller for the contacts page.
    /// </summary>
    [Authorize]
    public class ContactsController : Controller
    {
        // field
        private readonly ApplicationDbContext _context;

        // constructor injection: inject services
        public ContactsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Contacts
        /// <summary>
        /// Displays a view of all contacts.
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Index()
        {
              return View(await _context.Contacts.ToListAsync());
        }

        // GET: Contacts/Details/5
        /// <summary>
        /// Displays data associated to the specific id.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Contacts == null)
            {
                return NotFound();
            }

            var contactInfo = await _context.Contacts
                .FirstOrDefaultAsync(m => m.Id == id);
            if (contactInfo == null)
            {
                return NotFound();
            }

            return View(contactInfo);
        }

        // GET: Contacts/Create
        /// <summary>
        /// Create a new contact.
        /// </summary>
        /// <returns></returns>
        public IActionResult Create()
        {
            return View();
        }

        // POST: Contacts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        /// <summary>
        /// Add and save to database after validation.
        /// </summary>
        /// <param name="contactInfo"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FirstName,LastName,PhoneNumber,Email")] ContactInfo contactInfo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(contactInfo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(contactInfo);
        }

        // GET: Contacts/Edit/5
        /// <summary>
        /// Edit a specific event.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Contacts == null)
            {
                return NotFound();
            }

            var contactInfo = await _context.Contacts.FindAsync(id);
            if (contactInfo == null)
            {
                return NotFound();
            }
            return View(contactInfo);
        }

        // POST: Contacts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        /// <summary>
        /// Update and save contact to database after validation.
        /// </summary>
        /// <param name="id"></param>
        /// <param name="contactInfo"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,LastName,PhoneNumber,Email")] ContactInfo contactInfo)
        {
            if (id != contactInfo.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(contactInfo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ContactInfoExists(contactInfo.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(contactInfo);
        }

        // GET: Contacts/Delete/5
        /// <summary>
        /// Delete a specific contact.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Contacts == null)
            {
                return NotFound();
            }

            var contactInfo = await _context.Contacts
                .FirstOrDefaultAsync(m => m.Id == id);
            if (contactInfo == null)
            {
                return NotFound();
            }

            return View(contactInfo);
        }

        // POST: Contacts/Delete/5
        /// <summary>
        /// Update database after contact deletion.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Contacts == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Contacts'  is null.");
            }
            var contactInfo = await _context.Contacts.FindAsync(id);
            if (contactInfo != null)
            {
                _context.Contacts.Remove(contactInfo);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        /// <summary>
        /// Validation if content exists.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        private bool ContactInfoExists(int id)
        {
          return _context.Contacts.Any(e => e.Id == id);
        }
    }
}

PortfolioProject/Controllers/EventFormsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PortfolioProject.Data;
using PortfolioProject.Models;

namespace PortfolioProject.Controllers
{
    /// <summary>
    /// The controller for the event form page.
    /// </summary>
    [Authorize]
    public class EventFormsController : Controller
    {
        // field
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _environment;

        // constructor injection: inject services
        public EventFormsController(ApplicationDbContext context, IWebHostEnvironment environment)
        {
            _context = context;
            _environment = environment;
        }

        // GET: EventForms OFFSET & FETCH https://www.essentialsql.com/using-offset-and-fetch-with-the-order-by-clause/
        /// <summary>
        /// Displays a view of all events.
        /// </summary>
        /// <param name="viewModel"></param>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Index(EventFormsIndexViewModel viewModel, int? id)
        {
            // Make list flexible
            const int NumEventsToDisplayPerPage = 3;
            // Offset to use current page to figure out # of events to skip
            const int PageOffset = 1;
            // Get current page 
            /*
                if (id.HasValue)
                {
                    currPage = id.Value;
                }
                else
                {
                    currPage = 1;
                }
            */
            // int currPage = id.HasValue ? id.Value : 1;
            int currPage = id ?? 1; // lightbulb --> coalesce expression: https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/null-coalescing-operator
            // Total number of events out of the database
            int totalNumOfEvents = await _context.EventForms.CountAsync();
            // Round events up for items to be displayed
            double value = Math.Ceiling((double)totalNumOfEvents / NumEventsToDisplayPerPage);
            int lastPage = Convert.ToInt32(value);

            // Populate one event data details.
            List<EventFormsIndexViewModel> eventFormData =
                await (from ef in _context.EventForms
                       orderby ef.StartDateTime descending
                       select new EventFormsIndexViewModel
                       {
                           // map to model
                           EventFormId = ef.Id,
                           EventTitle = ef.EventTitle,
                           PhotoTitle = ef.PhotoTitle,
                           PhotoUrl = ef.PhotoUrl,
                           Description = ef.Description,
                           StartDateTime = ef.StartDateTime,
                           EndDateTime = ef.EndDateTime,
                           Category = ef.Category,
                           EventBy = ef.EventBy,
                           Location = ef.Location     
                       })
                       .Skip(NumEventsToDisplayPerPage * (currPage - PageOffset)) // skip 0 rows for the first page
                       .Take(NumEventsToDisplayPerPage) // take how many associated with const value
                       .ToListAsync();
            PaginationEventIndexViewModel eventListPage = new(eventFormData, lastPage, currPage);
            return View(eventListPage);
        }

        // GET: EventForms/Details/5
        /// <summary>
        /// Displays data associated to the specific event id.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.EventForms == null)
            {
                return NotFound();
            }
            // Populate the associated event id details.
            var eventForm = await 
                (from ef in _context.EventForms
                 orderby ef.Id
                 select new EventForm
                 {
                     // map to model
                     Id = ef.Id,
                     EventTitle = ef.EventTitle,
                     PhotoTitle = ef.PhotoTitle,
                     PhotoUrl = ef.PhotoUrl,
                     Description = ef.Description,
                     StartDateTime = ef.StartDateTime,
                     EndDateTime = ef.EndDateTime,
                     Category = ef.Category,
                     EventBy = ef.EventBy,
                     Location = ef.Location
                 }).FirstOrDefaultAsync(m => m.Id == id);
            if (eventForm == null)
            {
                return NotFound();
            }
            return View(eventForm);
        }

        // GET: EventForms/Create
        /// <summary>
        /// Create a new event form.
        /// </summary>
        /// <returns></returns>
        public IActionResult Create()
        {
            // Populate list of all contacts, categories and locations.
            CreateEventViewModel viewModel = new();
            viewModel.AllContacts = _context.Contacts.OrderBy(c => c.FirstName).ToList();
            viewModel.AllCategories = _context.Categories.OrderBy(i => i.EventId).ToList();
            viewModel.AllLocations = _context.Locations.OrderBy(l => l.LocationName).ToList();
            return View(viewModel);
        }

        // POST: EventForms/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        /// <summary>
        /// Add and save the event to database after validation.
        /// </summary>
        /// <param name="eventForm"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateEventViewModel eventForm)
        {
            // Create unique file name for uploading image.
            string fileName = Guid.NewGuid().ToString();
            fileName += fileName + Path.GetExtension(eventForm.UploadImage.FileName);

            // Save file to file system.
            string upoladPath = Path.Combine(_environment.WebRootPath, "images", fileName);

            // Create permission [using] Keyword calls and dispose automatically.
            using Stream fileStream = new FileStream(upoladPath, FileMode.Create);

            // Copy file
            await eventForm.UploadImage.CopyToAsync(fileStream);

            if (ModelState.IsValid)
            {
                // map CreateEventViewModel into newEvent
                EventForm newEvent = new()
                {
                    EventTitle = eventForm.EventTitle,
                    Description = eventForm.Description,
                    StartDateTime = eventForm.StartDateTime,
                    EndDateTime = eventForm.EndDateTime,
                    EventBy = new ContactInfo()
                    { 
                        Id = eventForm.ChosenContact
                    },
                    Category = new EventType()
                    { 
                        EventId = eventForm.ChosenCategory
                    },
                    Location = new Location()
                    { 
                        LocationId = eventForm.ChosenLocation
                    },
                    PhotoTitle = eventForm.PhotoTitle,
                    PhotoUrl = fileName
                };

                // The entity state has not changed from the existing models
                _context.Entry(newEvent.EventBy).State = EntityState.Unchanged;
                _context.Entry(newEvent.Category).State = EntityState.Unchanged;
                _context.Entry(newEvent.Location).State = EntityState.Unchanged;

                _context.Add(newEvent);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            eventForm.AllContacts = _context.Contacts.OrderBy(c => c.FirstName).ToList();
            eventForm.AllLocations = _context.Locations.OrderBy(l => l.LocationName).ToList();
            eventForm.AllCategories = _context.Categories.OrderBy(i => i.EventId).ToList();
            return View(eventForm);
        }

        // GET: EventForms/Edit/5
        /// <summary>
        /// Edit a specific event.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.EventForms == null)
            {
                return NotFound();
            }

            var eventForm = await _context.EventForms.FindAsync(id);
            if (eventForm == null)
            {
                return NotFound();
            }
            return View(eventForm);
        }

        // POST: EventForms/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        /// <summary>
        /// Update and save event to database after validation.
        /// </summary>
        /// <param name="id"></param>
        /// <param name="eventForm"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, EventForm eventForm)
        {
            if (id != eventForm.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(eventForm);

PortfolioProject/Views/EventForms/Create.cshtml
@model PortfolioProject.Models.CreateEventViewModel

@{
    ViewData["Title"] = "Create";

    // Create selected list 
    List<SelectListItem> contactsSelectList = new();
    List<SelectListItem> locationSelectList = new();
    List<SelectListItem> categorySelectList = new();

    // Get contacts
    foreach (ContactInfo contacts in Model.AllContacts)
    {
        // Make a list of select items
        contactsSelectList.Add
        (
            new SelectListItem()
            { 
                Value = contacts.Id.ToString(),
                Text = contacts.FirstName
            }
        );
    }

    // Get locations
    foreach (Location locations in Model.AllLocations)
    {
        // Make a list of select items
        locationSelectList.Add
        (
            new SelectListItem()
            {
                Value = locations.LocationId.ToString(),
                Text = locations.LocationName
            }
        );
    }

    // Get category
    foreach (EventType category in Model.AllCategories)
    {
        // Make a list of select items
        categorySelectList.Add
        (
            new SelectListItem()
            {
                Value = category.EventId.ToString(),
                Text = category.Category
            }
        );
    }
}

<h1>Create</h1>

<h4>Event Form</h4>
<a class="form-group btn btn-outline-primary" asp-area="" asp-controller="Contacts" asp-action="Create">Create Contact</a>
<a class="form-group btn btn-outline-primary" asp-area="" asp-controller="Locations" asp-action="Create">Add Locations</a>
<a class="form-group btn btn-outline-primary" asp-area="" asp-controller="EventTypes" asp-action="Create">Categories</a>
<hr />
<div class="row">
    <div class="col-md-6">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="EventTitle" class="control-label"></label>
                <input asp-for="EventTitle" class="form-control" />
                <span asp-validation-for="EventTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDateTime" class="control-label"></label>
                <input asp-for="StartDateTime" class="form-control" />
                <span asp-validation-for="StartDateTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDateTime" class="control-label"></label>
                <input asp-for="EndDateTime" class="form-control" />
                <span asp-validation-for="EndDateTime" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <select asp-for="ChosenContact">
                    @foreach(ContactInfo contact in Model.AllContacts)
                    {
                        <option value="@contact.Id">@contact.FirstName @contact.LastName</option>
                    }
                </select>
            </div>
            <br />
            <div class="form-group">
                <select asp-for="ChosenLocation">
                    @foreach(Location location in Model.AllLocations)
                    {
                        <option value="@location.LocationId">@location.LocationName</option>
                    }
                </select>
            </div>
            <br />
            <div class="form-group">
                <select asp-for="ChosenCategory"> 
                    @foreach (EventType category in Model.AllCategories)
                    {
                        <option value="@category.EventId">@category.Category</option>
                    }
                </select>
            </div>
             <div class="form-group">
                <label asp-for="PhotoTitle" class="control-label"></label>
                <input asp-for="PhotoTitle" class="form-control" />
                <span asp-validation-for="PhotoTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UploadImage" class="control-label"></label>
                <input asp-for="UploadImage" class="form-control" />
                <span asp-validation-for="UploadImage" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-outline-success" />
                <a class="btn btn-outline-danger" asp-action="Index">Cancel</a>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

PortfolioProject/Views/EventForms/Delete.cshtml
@model PortfolioProject.Models.EventForm

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>EventForm</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EventTitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EventTitle)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

PortfolioProject/Views/EventForms/Details.cshtml
@model PortfolioProject.Models.EventForm

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Event Form</h4>
    <hr />
    <dl class="row"> 
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Category.Category)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EventTitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EventTitle)     
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayFor(model => model.PhotoTitle)
        </dt>
        <dd class = "col-sm-10">
            <img height="200" src="~/images/@Model.PhotoUrl" />  
        </dd>
          <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)     
        </dd>
          <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDateTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDateTime)     
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EndDateTime)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EndDateTime)
        </dd> 
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EventBy.FirstName)
            @Html.DisplayNameFor(model => model.EventBy.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EventBy.FirstName)
            @Html.DisplayFor(model => model.EventBy.LastName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EventBy.PhoneNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EventBy.PhoneNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Location.LocationName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Location.LocationName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Location.StreetAddress)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Location.StreetAddress)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Location.City),           
            @Html.DisplayNameFor(model => model.Location.State) 
            @Html.DisplayNameFor(model => model.Location.Zip)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Location.City),
            @Html.DisplayFor(model => model.Location.State) 
            @Html.DisplayFor(model => model.Location.Zip)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

PortfolioProject/Views/EventForms/Edit.cshtml
@model PortfolioProject.Models.EventForm

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>EventForm</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="EventTitle" class="control-label"></label>
                <input asp-for="EventTitle" class="form-control" />
                <span asp-validation-for="EventTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDateTime" class="control-label"></label>
                <input asp-for="StartDateTime" class="form-control" />
                <span asp-validation-for="StartDateTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDateTime" class="control-label"></label>
                <input asp-for="EndDateTime" class="form-control" />
                <span asp-validation-for="EndDateTime" class="text-danger"></span>
            </div><br />

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

PortfolioProject/Views/EventForms/Index.cshtml
@model PortfolioProject.Models.PaginationEventIndexViewModel

@{
    ViewData["Title"] = "Events";
}

<h1>Events</h1>

<p>
    <a class="btn btn-primary" asp-controller="EventForms" asp-action="Create">Add New Event</a>
</p>

@if (Model.EventForms.Count > 0)
{ 
<table class="table table-striped table-hover">
    <thead>
			<tr>
			<th>
				@Html.DisplayNameFor(model => model.EventForms[0].Category.Category)
			</th>
            	<th>
				@Html.DisplayNameFor(model => model.EventForms[0].PhotoTitle)
			</th>
                <th>
                    @Html.DisplayNameFor(model => model.EventForms[0].PhotoUrl)
                </th>
            <th>
                @Html.DisplayNameFor(model => model.EventForms[0].EventTitle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EventForms[0].Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EventForms[0].StartDateTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EventForms[0].EndDateTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EventForms[0].EventBy.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EventForms[0].EventBy.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EventForms[0].EventBy.PhoneNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EventForms[0].Location.LocationName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EventForms[0].Location.StreetAddress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EventForms[0].Location.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EventForms[0].Location.State)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EventForms[0].Location.Zip)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.EventForms) 
        {
        <tr>
			<td>
				@Html.DisplayFor(modelItem => item.Category.Category)
			</td>
            	<td>
				@Html.DisplayFor(modelItem => item.PhotoTitle)
			</td>
            <td>
                <img height="200" src="~/images/@item.PhotoUrl" alt="@item.PhotoTitle">
            </td>
			<td>
                @Html.DisplayFor(modelItem => item.EventTitle)
            </td>           

            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartDateTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndDateTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EventBy.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EventBy.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EventBy.PhoneNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Location.LocationName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Location.StreetAddress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Location.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Location.State)
            <td>
                @Html.DisplayFor(modelItem => item.Location.Zip)
            </td>
            <td>
                <a type="button" class="btn btn-outline-primary" asp-action="Edit" asp-route-id="@item.EventFormId">Edit</a> 
                <a type="button" class="btn btn-outline-success" asp-action="Details" asp-route-id="@item.EventFormId">Details</a> 
                <a type="button" class="btn btn-outline-danger" asp-action="Delete" asp-route-id="@item.EventFormId">Delete</a>
            </td>
        </tr>
        }
    </tbody>
</table>
}
else
{
 <h2>There are no more events.</h2>
}

<nav aria-label="Event List Pages">
    <ul class="pagination">
    @for (int i = 1; i <= Model.LastPage; i++)
    {
        if (i == Model.CurrentPage)
        {
            <li class="page-item active">
                <a class="page-link">@i</a>
            </li>
        }
        else 
        {
            <li class="page-item">
                <a class="page-link" asp-action="Index" asp-route-id="@i">@i</a>
            </li>
        }
    }
    </ul>
</nav>